import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

export const generateBillPDF = (bill, entries, partners, billType) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(15, 118, 110); // Primary teal color
  doc.text('BillBird', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Secondary color
  doc.text('Bill Dividing App', 14, 30);
  
  // Bill Title
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59); // Text color
  doc.text(bill.title, 14, 45);
  
  // Bill Details
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  
  const details = [
    ['Bill Type:', billType?.name || 'Unknown'],
    ['Bill Date:', format(new Date(bill.billDate), 'dd MMM yyyy')],
    ['Total Amount:', `₹${bill.totalAmount?.toFixed(2)}`],
    ['Status:', bill.status.charAt(0).toUpperCase() + bill.status.slice(1)]
  ];
  
  if (bill.dueDate) {
    details.push(['Due Date:', format(new Date(bill.dueDate), 'dd MMM yyyy')]);
  }
  
  if (bill.description) {
    details.push(['Description:', bill.description]);
  }
  
  let yPos = 55;
  details.forEach(([label, value]) => {
    doc.setTextColor(100, 116, 139);
    doc.text(label, 14, yPos);
    doc.setTextColor(30, 41, 59);
    doc.text(value, 60, yPos);
    yPos += 7;
  });
  
  // Partner Split Table
  yPos += 10;
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('Partner Split Details', 14, yPos);
  
  yPos += 5;
  
  // Prepare table data
  const tableData = entries.map(entry => {
    const partner = partners.find(p => p.id === entry.partnerId);
    const partnerName = partner ? partner.name : 'Unknown';
    
    const row = [
      partnerName,
      `₹${entry.splitAmount?.toFixed(2)}`,
      entry.paid ? 'Paid' : 'Pending'
    ];
    
    // Add usage details for usage-based bills
    if (billType?.category === 'usage') {
      row.splice(1, 0, 
        entry.lastUsage?.toString() || '0',
        entry.currentUsage?.toString() || '0',
        Math.max(0, (entry.currentUsage || 0) - (entry.lastUsage || 0)).toString()
      );
    }
    
    return row;
  });
  
  // Table headers
  const headers = ['Partner', 'Amount', 'Status'];
  if (billType?.category === 'usage') {
    headers.splice(1, 0, 'Last Usage', 'Current Usage', 'Usage');
  }
  
  // Generate table
  doc.autoTable({
    head: [headers],
    body: tableData,
    startY: yPos,
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    headStyles: {
      fillColor: [15, 118, 110],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [240, 253, 250]
    },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 30, halign: 'right' },
      2: { cellWidth: 25, halign: 'center' }
    }
  });
  
  // Summary
  const finalY = doc.lastAutoTable.finalY + 10;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Summary', 14, finalY);
  
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  
  const totalPaid = entries.filter(e => e.paid).reduce((sum, e) => sum + (e.splitAmount || 0), 0);
  const totalPending = entries.filter(e => !e.paid).reduce((sum, e) => sum + (e.splitAmount || 0), 0);
  
  doc.text(`Total Amount: ₹${bill.totalAmount?.toFixed(2)}`, 14, finalY + 8);
  doc.text(`Total Paid: ₹${totalPaid.toFixed(2)}`, 14, finalY + 15);
  doc.text(`Total Pending: ₹${totalPending.toFixed(2)}`, 14, finalY + 22);
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by BillBird on ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`,
    14,
    pageHeight - 10
  );
  
  // Save PDF
  const fileName = `${bill.title.replace(/[^a-z0-9]/gi, '_')}_${format(new Date(bill.billDate), 'yyyy-MM-dd')}.pdf`;
  doc.save(fileName);
};

export const generateAllBillsPDF = (bills, billEntries, partners, billTypes) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(15, 118, 110);
  doc.text('BillBird - Bills Report', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated on ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, 14, 30);
  
  // Summary
  const totalAmount = bills.reduce((sum, bill) => sum + (bill.totalAmount || 0), 0);
  const paidBills = bills.filter(b => b.status === 'paid').length;
  const pendingBills = bills.filter(b => b.status === 'pending').length;
  
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text(`Total Bills: ${bills.length}`, 14, 45);
  doc.text(`Total Amount: ₹${totalAmount.toFixed(2)}`, 14, 52);
  doc.text(`Paid: ${paidBills} | Pending: ${pendingBills}`, 14, 59);
  
  // Bills Table
  const tableData = bills.map(bill => {
    const billType = billTypes.find(t => t.id === bill.billTypeId);
    return [
      bill.title,
      billType?.name || 'Unknown',
      `₹${bill.totalAmount?.toFixed(2)}`,
      format(new Date(bill.billDate), 'dd/MM/yyyy'),
      bill.status.charAt(0).toUpperCase() + bill.status.slice(1)
    ];
  });
  
  doc.autoTable({
    head: [['Title', 'Type', 'Amount', 'Date', 'Status']],
    body: tableData,
    startY: 70,
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    headStyles: {
      fillColor: [15, 118, 110],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [240, 253, 250]
    }
  });
  
  // Save PDF
  const fileName = `billbird_report_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  doc.save(fileName);
};
